spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/api/chats/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/api/messages/**

        - id: socket-service
          uri: lb://socket-service
          predicates:
            - Path=/ws/**
          metadata:
            websocket: true
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

        #  chỉ giữ 1 route presence
        - id: presence-service
          uri: lb://socket-service
          predicates:
            - Path=/api/presence/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**

        - id: media-service
          uri: lb://media-service
          predicates:
            - Path=/api/media/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,env,prometheus
      base-path: /actuator

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

app:
  jwt:
    secret: dsajkdhaskjdhakjdhqwiueyqweuiyqweuiyqweuiyqweuiyqweuiyqweuiyqweujkjhhjhgfdfghhertuithdfgkjhflkjhgjji
