server:
  port: 8086

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/chatdb

app:
  minio:
    endpoint: http://localhost:9000
    accessKey: minioadmin
    secretKey: minioadmin123
    bucket: chat-media
    thumbsPrefix: thumbs/

  media:
    max-size-bytes: 52428800 # 50MB
    allowed-content-types: "image/jpeg,image/png,image/webp,video/mp4,audio/mpeg,application/pdf"

  kafka:
    enabled: true
    topic:
      media-uploaded: chat.media.uploaded

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
