server:
  port: 8083

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chatdb

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  kafka:
    topic:
      message-created: chat.message.created

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
