server:
  port: 8085

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/chatdb
    redis:
      host: 127.0.0.1
      port: 6379

  cloud:
    openfeign:
      micrometer:
        enable: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: tn.cuongdk.chat.gateway.startermodel.dto.resquest.message_service.MessageCreatedEvent
        spring.json.trusted.packages: "tn.cuongdk.chat.*"
    listener:
      observation-enabled: true
    template:
      observation-enabled: true

app:
  kafka:
    topic:
      message-created: chat.message.created
  redis:
    presence-prefix: "online:"
    active-room-prefix: "active_room:"
    unread-prefix: "unread:"
    lastread-prefix: "last_read:"
    processed-prefix: "processed_msg:"
    processed-ttl-days: 7

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    metrics:
      distribution:
        percentiles-histogram:
          http.server.requests: true
    tags:
      application: ${spring.application.name}
