server:
  port: 8084

spring:
  application:
    name: socket-service
  data:
    redis:
      host: 127.0.0.1
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: socket-service-group
      auto-offset-reset: latest

      # ✅ bọc deserializer để không chết vì SerializationException
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        # delegate thật sự
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

        # ✅ bỏ qua __TypeId__ (đề phòng record cũ/khác package)
        spring.json.use.type.headers: false

        # ✅ ép deserialize về class event đang dùng trong socket-service (starter-model)
        spring.json.value.default.type: tn.cuongdk.chat.gateway.startermodel.dto.resquest.message_service.MessageCreatedEvent

        # ✅ chỉ trust package của bạn (đừng dùng "*")
        spring.json.trusted.packages: "tn.cuongdk.chat.*"

app:
  kafka:
    topic:
      message-created: chat.message.created
  redis:
    presence-prefix: "online:"
    presence-ttl-seconds: 90
    active-room-prefix: "active_room:"
    active-room-ttl-seconds: 90
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: dsajkdhaskjdhakjdhqwiueyqweuiyqweuiyqweuiyqweuiyqweuiyqweuiyqweujkjhhjhgfdfghhertuithdfgkjhflkjhgjji
