server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/user_service_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true

  data:
    redis:
      host: 127.0.0.1
      port: 6379


app:
  kafka:
    topic:
      friend-request-created: chat.friend.request.created
      friend-request-accepted: chat.friend.request.accepted
      password-reset-requested: chat.user.password.reset.requested

  security:
    token-blacklist-prefix: "bl:"
    user-invalid-before-prefix: "inv:"
    user-invalid-before-ttl-days: 30

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
    tags:
      application: ${spring.application.name}


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
