server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/user_service_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    metrics:
      distribution:
        percentiles-histogram:
          http.server.requests: true
    tags:
      application: ${spring.application.name}


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
